/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package conversor;

import java.awt.Graphics;
import java.awt.Image;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.json.JSONException;
import org.json.JSONObject;

/**
 *
 * @author germa
 */
public class exchange extends javax.swing.JFrame {

    // Método para obtener los símbolos de las tasas de cambio de la API de apilayer y agregarlos a los ComboBox divisa_1 y divisa_2
    private void agregarSimbolos() {
        String simbolosJSON = ApiService.obtenerSimbolos();

        try {
            JSONObject jsonObject = new JSONObject(simbolosJSON);
            JSONObject symbols = jsonObject.getJSONObject("symbols");
            Iterator<String> keys = symbols.keys();
            ArrayList<String> simbolosList = new ArrayList<String>();
            while (keys.hasNext()) {
                String key = keys.next();
                String value = symbols.getString(key);
                String simbolo = key + ": " + value;
                simbolosList.add(simbolo);
            }

            // Ordenar la lista de símbolos alfabéticamente
            Collections.sort(simbolosList);

            String[] simbolosArray = simbolosList.toArray(new String[simbolosList.size()]);
            DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>(simbolosArray);
            divisa_1.setModel(model1);

            String[] simbolosArray2 = simbolosList.toArray(new String[simbolosList.size()]);
            DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>(simbolosArray2);
            divisa_2.setModel(model2);

        } catch (JSONException e) {
            System.out.println("Error parsing JSON: " + e.getMessage());
        }
    }

    /**
     * Creates new form Divisas
     */
    double valor;
    int xMouse, yMouse;

    public exchange() {

        initComponents();
        agregarSimbolos();

        peso_1.addItem("kg: Kilogramo");
        peso_1.addItem("gr: Gramo");
        peso_1.addItem("hg: Hectogramo");
        peso_1.addItem("da: Decagramo");
        peso_1.addItem("dg: Decigramo");
        peso_1.addItem("cd: Centigramo");
        peso_1.addItem("mg: Miligramo");
        peso_1.addItem("lb: Libra");

        peso_2.addItem("kg: Kilogramo");
        peso_2.addItem("gr: Gramo");
        peso_2.addItem("hg: Hectogramo");
        peso_2.addItem("da: Decagramo");
        peso_2.addItem("dg: Decigramo");
        peso_2.addItem("cd: Centigramo");
        peso_2.addItem("mg: Miligramo");
        peso_2.addItem("lb: Libra");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JPanel();
        panel_title = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        paneles = new javax.swing.JTabbedPane();
        panel_exchange = new FondoPanel();
        texto_divisa = new javax.swing.JTextField();
        convertir = new javax.swing.JButton();
        texto_conversor = new javax.swing.JLabel();
        scroll_resultado = new javax.swing.JScrollPane();
        resultado1 = new javax.swing.JTextArea();
        panel_menu = new javax.swing.JPanel();
        divisa = new button.MyButton();
        peso = new button.MyButton();
        traductor = new button.MyButton();
        divisa_1 = new combo_suggestion.ComboBoxSuggestion();
        divisa_2 = new combo_suggestion.ComboBoxSuggestion();
        panel_peso = new FondoPanel2();
        texto_peso = new javax.swing.JTextField();
        peso_1 = new combo_suggestion.ComboBoxSuggestion();
        peso_2 = new combo_suggestion.ComboBoxSuggestion();
        convertir1 = new javax.swing.JButton();
        texto_conversor1 = new javax.swing.JLabel();
        scroll_resultado1 = new javax.swing.JScrollPane();
        resultado2 = new javax.swing.JTextArea();
        panel_menu1 = new javax.swing.JPanel();
        divisa1 = new button.MyButton();
        peso1 = new button.MyButton();
        traductor1 = new button.MyButton();
        panel_traductor = new FondoPanel3();
        texto_conversor2 = new javax.swing.JLabel();
        panel_menu2 = new javax.swing.JPanel();
        divisa2 = new button.MyButton();
        peso2 = new button.MyButton();
        traductor2 = new button.MyButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        home.setBackground(java.awt.SystemColor.textHighlight);
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_title.setBackground(java.awt.SystemColor.textHighlight);
        panel_title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_titleMouseDragged(evt);
            }
        });
        panel_title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_titleMousePressed(evt);
            }
        });

        close.setFont(new java.awt.Font("Dialog", 0, 25)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        title.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("CONVERSOR");

        javax.swing.GroupLayout panel_titleLayout = new javax.swing.GroupLayout(panel_title);
        panel_title.setLayout(panel_titleLayout);
        panel_titleLayout.setHorizontalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_titleLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_titleLayout.setVerticalGroup(
            panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_titleLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_titleLayout.createSequentialGroup()
                        .addComponent(close)
                        .addGap(26, 26, 26))
                    .addGroup(panel_titleLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(title)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        home.add(panel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        panel_exchange.setBackground(new java.awt.Color(255, 255, 255));

        texto_divisa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        texto_divisa.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.textHighlight, 5, true));
        texto_divisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_divisaActionPerformed(evt);
            }
        });
        texto_divisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_divisaKeyTyped(evt);
            }
        });

        convertir.setBackground(java.awt.SystemColor.textHighlight);
        convertir.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        convertir.setForeground(new java.awt.Color(255, 255, 255));
        convertir.setText("Exchange");
        convertir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        convertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convertir.setMaximumSize(new java.awt.Dimension(518, 518));
        convertir.setMinimumSize(new java.awt.Dimension(518, 518));
        convertir.setPreferredSize(new java.awt.Dimension(518, 518));
        convertir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convertirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convertirMouseExited(evt);
            }
        });
        convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertirActionPerformed(evt);
            }
        });

        texto_conversor.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        texto_conversor.setForeground(java.awt.SystemColor.textHighlight);
        texto_conversor.setText("Convertir A:");

        resultado1.setColumns(5);
        resultado1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        resultado1.setLineWrap(true);
        resultado1.setRows(1);
        resultado1.setTabSize(2);
        resultado1.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.textHighlight, 5, true));
        resultado1.setMargin(new java.awt.Insets(20, 20, 2, 6));
        scroll_resultado.setViewportView(resultado1);

        panel_menu.setBackground(new java.awt.Color(0, 120, 215,0));

        divisa.setForeground(new java.awt.Color(255, 255, 255));
        divisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dolar.png"))); // NOI18N
        divisa.setBorderColor(new java.awt.Color(255, 255, 255));
        divisa.setColorClick(new java.awt.Color(255, 255, 255));
        divisa.setColorOver(new java.awt.Color(255, 255, 255));
        divisa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        divisa.setMargin(new java.awt.Insets(0, 0, 0, 0));
        divisa.setRadius(50);
        divisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisaMouseClicked(evt);
            }
        });

        peso.setBackground(java.awt.SystemColor.textHighlight);
        peso.setForeground(new java.awt.Color(255, 255, 255));
        peso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peso.png"))); // NOI18N
        peso.setBorderColor(java.awt.SystemColor.textHighlight);
        peso.setColor(java.awt.SystemColor.textHighlight);
        peso.setColorClick(java.awt.SystemColor.textHighlight);
        peso.setColorOver(java.awt.SystemColor.textHighlight);
        peso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        peso.setMargin(new java.awt.Insets(0, 0, 0, 0));
        peso.setRadius(50);
        peso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesoMouseClicked(evt);
            }
        });

        traductor.setBackground(java.awt.SystemColor.textHighlight);
        traductor.setForeground(new java.awt.Color(255, 255, 255));
        traductor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/traductor.png"))); // NOI18N
        traductor.setBorderColor(java.awt.SystemColor.textHighlight);
        traductor.setColor(java.awt.SystemColor.textHighlight);
        traductor.setColorClick(java.awt.SystemColor.textHighlight);
        traductor.setColorOver(java.awt.SystemColor.textHighlight);
        traductor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        traductor.setMargin(new java.awt.Insets(0, 0, 0, 0));
        traductor.setRadius(50);
        traductor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                traductorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menuLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traductor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(divisa, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(peso, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(traductor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        divisa_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 206, 154), 2));
        divisa_1.setEditable(false);
        divisa_1.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N

        divisa_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 206, 154), 2));
        divisa_2.setEditable(false);
        divisa_2.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N

        javax.swing.GroupLayout panel_exchangeLayout = new javax.swing.GroupLayout(panel_exchange);
        panel_exchange.setLayout(panel_exchangeLayout);
        panel_exchangeLayout.setHorizontalGroup(
            panel_exchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exchangeLayout.createSequentialGroup()
                .addComponent(panel_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_exchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_exchangeLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(panel_exchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_exchangeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(texto_conversor)))
                    .addGroup(panel_exchangeLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(panel_exchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(scroll_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_exchangeLayout.createSequentialGroup()
                                .addComponent(divisa_1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(texto_divisa, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panel_exchangeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(divisa_2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        panel_exchangeLayout.setVerticalGroup(
            panel_exchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_exchangeLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(panel_exchangeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(texto_divisa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisa_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(texto_conversor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(divisa_2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(scroll_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(panel_exchangeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        paneles.addTab("tab1", panel_exchange);

        panel_peso.setBackground(java.awt.SystemColor.inactiveCaption);

        texto_peso.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        texto_peso.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.textHighlight, 5, true));
        texto_peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texto_pesoActionPerformed(evt);
            }
        });
        texto_peso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                texto_pesoKeyTyped(evt);
            }
        });

        peso_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 231, 172), 2));
        peso_1.setEditable(false);
        peso_1.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N

        peso_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 231, 172), 2));
        peso_2.setEditable(false);
        peso_2.setFont(new java.awt.Font("Dialog", 2, 16)); // NOI18N

        convertir1.setBackground(java.awt.SystemColor.textHighlight);
        convertir1.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        convertir1.setForeground(new java.awt.Color(255, 255, 255));
        convertir1.setText("Exchange");
        convertir1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        convertir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        convertir1.setMaximumSize(new java.awt.Dimension(518, 518));
        convertir1.setMinimumSize(new java.awt.Dimension(518, 518));
        convertir1.setPreferredSize(new java.awt.Dimension(518, 518));
        convertir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                convertir1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                convertir1MouseExited(evt);
            }
        });
        convertir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertir1ActionPerformed(evt);
            }
        });

        texto_conversor1.setFont(new java.awt.Font("Dialog", 1, 25)); // NOI18N
        texto_conversor1.setForeground(java.awt.SystemColor.textHighlight);
        texto_conversor1.setText("Convertir A:");

        resultado2.setColumns(5);
        resultado2.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        resultado2.setLineWrap(true);
        resultado2.setRows(1);
        resultado2.setTabSize(2);
        resultado2.setBorder(new javax.swing.border.LineBorder(java.awt.SystemColor.textHighlight, 5, true));
        resultado2.setMargin(new java.awt.Insets(20, 20, 2, 6));
        scroll_resultado1.setViewportView(resultado2);

        panel_menu1.setBackground(new java.awt.Color(0, 120, 215,0));

        divisa1.setBackground(java.awt.SystemColor.textHighlight);
        divisa1.setForeground(new java.awt.Color(255, 255, 255));
        divisa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dolar.png"))); // NOI18N
        divisa1.setBorderColor(java.awt.SystemColor.textHighlight);
        divisa1.setColor(java.awt.SystemColor.textHighlight);
        divisa1.setColorClick(java.awt.SystemColor.textHighlight);
        divisa1.setColorOver(java.awt.SystemColor.textHighlight);
        divisa1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        divisa1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        divisa1.setRadius(50);
        divisa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisa1MouseClicked(evt);
            }
        });

        peso1.setForeground(new java.awt.Color(255, 255, 255));
        peso1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peso.png"))); // NOI18N
        peso1.setBorderColor(new java.awt.Color(255, 255, 255));
        peso1.setColorClick(new java.awt.Color(255, 255, 255));
        peso1.setColorOver(new java.awt.Color(255, 255, 255));
        peso1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        peso1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        peso1.setRadius(50);
        peso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peso1MouseClicked(evt);
            }
        });

        traductor1.setBackground(java.awt.SystemColor.textHighlight);
        traductor1.setForeground(new java.awt.Color(255, 255, 255));
        traductor1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/traductor.png"))); // NOI18N
        traductor1.setBorderColor(java.awt.SystemColor.textHighlight);
        traductor1.setColor(java.awt.SystemColor.textHighlight);
        traductor1.setColorClick(java.awt.SystemColor.textHighlight);
        traductor1.setColorOver(java.awt.SystemColor.textHighlight);
        traductor1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        traductor1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        traductor1.setRadius(50);
        traductor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                traductor1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_menu1Layout = new javax.swing.GroupLayout(panel_menu1);
        panel_menu1.setLayout(panel_menu1Layout);
        panel_menu1Layout.setHorizontalGroup(
            panel_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panel_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traductor1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        panel_menu1Layout.setVerticalGroup(
            panel_menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menu1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(divisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(peso1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(traductor1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_pesoLayout = new javax.swing.GroupLayout(panel_peso);
        panel_peso.setLayout(panel_pesoLayout);
        panel_pesoLayout.setHorizontalGroup(
            panel_pesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pesoLayout.createSequentialGroup()
                .addComponent(panel_menu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_pesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_pesoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_pesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_pesoLayout.createSequentialGroup()
                                .addComponent(texto_conversor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panel_pesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(peso_1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peso_2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panel_pesoLayout.createSequentialGroup()
                                .addGap(0, 34, Short.MAX_VALUE)
                                .addComponent(convertir1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(scroll_resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pesoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(texto_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );
        panel_pesoLayout.setVerticalGroup(
            panel_pesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pesoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_menu1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_pesoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(peso_1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(texto_peso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_pesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peso_2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto_conversor1))
                .addGap(33, 33, 33)
                .addGroup(panel_pesoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(convertir1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(89, 89, 89))
        );

        paneles.addTab("tab2", panel_peso);

        panel_traductor.setBackground(java.awt.SystemColor.controlHighlight);

        texto_conversor2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        texto_conversor2.setForeground(new java.awt.Color(94, 103, 77));
        texto_conversor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto_conversor2.setText("coming soon... Wait for it!");
        texto_conversor2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_menu2.setBackground(new java.awt.Color(0, 120, 215,0));

        divisa2.setBackground(java.awt.SystemColor.textHighlight);
        divisa2.setForeground(new java.awt.Color(255, 255, 255));
        divisa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dolar.png"))); // NOI18N
        divisa2.setBorderColor(java.awt.SystemColor.textHighlight);
        divisa2.setColor(java.awt.SystemColor.textHighlight);
        divisa2.setColorClick(java.awt.SystemColor.textHighlight);
        divisa2.setColorOver(java.awt.SystemColor.textHighlight);
        divisa2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        divisa2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        divisa2.setRadius(50);
        divisa2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divisa2MouseClicked(evt);
            }
        });

        peso2.setBackground(java.awt.SystemColor.textHighlight);
        peso2.setForeground(new java.awt.Color(255, 255, 255));
        peso2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/peso.png"))); // NOI18N
        peso2.setBorderColor(java.awt.SystemColor.textHighlight);
        peso2.setColor(java.awt.SystemColor.textHighlight);
        peso2.setColorClick(java.awt.SystemColor.textHighlight);
        peso2.setColorOver(java.awt.SystemColor.textHighlight);
        peso2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        peso2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        peso2.setRadius(50);
        peso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                peso2MouseClicked(evt);
            }
        });

        traductor2.setForeground(new java.awt.Color(255, 255, 255));
        traductor2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/traductor.png"))); // NOI18N
        traductor2.setBorderColor(new java.awt.Color(255, 255, 255));
        traductor2.setColorClick(new java.awt.Color(255, 255, 255));
        traductor2.setColorOver(new java.awt.Color(255, 255, 255));
        traductor2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        traductor2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        traductor2.setRadius(50);
        traductor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                traductor2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panel_menu2Layout = new javax.swing.GroupLayout(panel_menu2);
        panel_menu2.setLayout(panel_menu2Layout);
        panel_menu2Layout.setHorizontalGroup(
            panel_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu2Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(panel_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(traductor2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peso2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        panel_menu2Layout.setVerticalGroup(
            panel_menu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menu2Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(divisa2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(peso2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(traductor2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/building.gif"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 100));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout panel_traductorLayout = new javax.swing.GroupLayout(panel_traductor);
        panel_traductor.setLayout(panel_traductorLayout);
        panel_traductorLayout.setHorizontalGroup(
            panel_traductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_traductorLayout.createSequentialGroup()
                .addComponent(panel_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panel_traductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_traductorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texto_conversor2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_traductorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );
        panel_traductorLayout.setVerticalGroup(
            panel_traductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_traductorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_traductorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_menu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_traductorLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(texto_conversor2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );

        paneles.addTab("tab3", panel_traductor);

        home.add(paneles, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 55, 590, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(589, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void convertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertirActionPerformed
        // TODO add your handling code here:
        String divisa1 = "";
        String divisa2 = "";
        double cantidad = 0.0;

        // Verificar que se hayan seleccionado valores en los ComboBox
        if (divisa_1.getSelectedIndex() != -1 && divisa_2.getSelectedIndex() != -1) {
            // Obtener las abreviaturas de las divisas seleccionadas
            String divisa1Seleccionada = divisa_1.getSelectedItem().toString();
            String divisa2Seleccionada = divisa_2.getSelectedItem().toString();
            if (divisa1Seleccionada.length() >= 3 && divisa2Seleccionada.length() >= 3) {
                divisa1 = divisa1Seleccionada.substring(0, 3);
                divisa2 = divisa2Seleccionada.substring(0, 3);
            } else {
                System.out.println("Ingresa una divisa válida");
                return;
            }
        } else {
            System.out.println("Selecciona una divisa");
            return;
        }

        // Verificar que se haya ingresado un valor numérico en el campo de texto
        try {
            cantidad = Double.parseDouble(texto_divisa.getText());
        } catch (NumberFormatException e) {
            System.out.println("Ingresa un valor numérico válido");
            return;
        }

        // Llamar a la API de apilayer para obtener el resultado de la conversión
        String resultadoJSON = ApiConvert.convertir(divisa1, divisa2, cantidad);
        try {
            JSONObject resultadoObj = new JSONObject(resultadoJSON);
            double resultado = resultadoObj.getDouble("result");
            /**
             * resultado1.setText(String.format("%.2f %s = %.2f %s", cantidad,
             * divisa1, resultado, divisa2));
             */
            resultado1.setText(String.format("%s", resultado + " " + divisa2));
        } catch (JSONException e) {
            System.out.println("Error parsing JSON: " + e.getMessage());
        }

    }//GEN-LAST:event_convertirActionPerformed

    private void convertirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertirMouseExited
        convertir.setBackground(new java.awt.Color(0, 98, 176));
        convertir.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_convertirMouseExited

    private void convertirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertirMouseEntered
        convertir.setBackground(new java.awt.Color(94, 103, 77));
        convertir.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_convertirMouseEntered

    private void texto_divisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_divisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_divisaActionPerformed

    private void texto_divisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_divisaKeyTyped
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
        } else if (validar == '.' && texto_divisa.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se puede ingresar un punto");
        }
    }//GEN-LAST:event_texto_divisaKeyTyped

    private void divisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisaMouseClicked
        paneles.setSelectedIndex(0);
    }//GEN-LAST:event_divisaMouseClicked

    private void pesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesoMouseClicked
        paneles.setSelectedIndex(1);
    }//GEN-LAST:event_pesoMouseClicked

    private void traductorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_traductorMouseClicked
        paneles.setSelectedIndex(2);
    }//GEN-LAST:event_traductorMouseClicked

    private void texto_pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texto_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texto_pesoActionPerformed

    private void texto_pesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_texto_pesoKeyTyped
        // TODO add your handling code here:
        char validar1 = evt.getKeyChar();

        if (Character.isLetter(validar1)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Ingresar solo números");
        } else if (validar1 == '.' && texto_peso.getText().contains(".")) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se puede ingresar un punto");
        }
    }//GEN-LAST:event_texto_pesoKeyTyped

    private void convertir1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertir1MouseEntered
        // TODO add your handling code here:
        convertir1.setBackground(new java.awt.Color(165, 157, 117));
        convertir1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_convertir1MouseEntered

    private void convertir1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_convertir1MouseExited
        // TODO add your handling code here:
        convertir1.setBackground(new java.awt.Color(0, 98, 176));
        convertir1.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_convertir1MouseExited

    private void convertir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertir1ActionPerformed
        // TODO add your handling code here:
        double Valor1 = Double.parseDouble(texto_peso.getText());

        int unidad = peso_1.getSelectedIndex();

        int unidadFinal = peso_2.getSelectedIndex();

        peso puente = new peso();
        puente.setValor1(Valor1);
        puente.setUnidad(unidad);
        puente.setUnidadFinal(unidadFinal);

        double resultadofinal1 = puente.convertir();

        String unidadFinalTexto = ((String) peso_2.getSelectedItem()).substring(0, 2);
        resultado2.setText("");
        resultado2.append(String.format("%.2f %s", resultadofinal1, unidadFinalTexto));
    }//GEN-LAST:event_convertir1ActionPerformed

    private void divisa1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisa1MouseClicked
        paneles.setSelectedIndex(0);
    }//GEN-LAST:event_divisa1MouseClicked

    private void peso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peso1MouseClicked
        paneles.setSelectedIndex(1);
    }//GEN-LAST:event_peso1MouseClicked

    private void traductor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_traductor1MouseClicked
        paneles.setSelectedIndex(2);
    }//GEN-LAST:event_traductor1MouseClicked

    private void divisa2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divisa2MouseClicked
        paneles.setSelectedIndex(0);
    }//GEN-LAST:event_divisa2MouseClicked

    private void peso2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_peso2MouseClicked
        paneles.setSelectedIndex(1);
    }//GEN-LAST:event_peso2MouseClicked

    private void traductor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_traductor2MouseClicked
        paneles.setSelectedIndex(2);
    }//GEN-LAST:event_traductor2MouseClicked

    private void panel_titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_titleMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panel_titleMousePressed

    private void panel_titleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_titleMouseDragged
        // TODO add your handling code here:
        int Y = evt.getYOnScreen();
        int X = evt.getXOnScreen();
        setLocation(X - xMouse, Y - yMouse);
    }//GEN-LAST:event_panel_titleMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exchange.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exchange().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JButton convertir;
    private javax.swing.JButton convertir1;
    private button.MyButton divisa;
    private button.MyButton divisa1;
    private button.MyButton divisa2;
    private combo_suggestion.ComboBoxSuggestion divisa_1;
    private combo_suggestion.ComboBoxSuggestion divisa_2;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_exchange;
    private javax.swing.JPanel panel_menu;
    private javax.swing.JPanel panel_menu1;
    private javax.swing.JPanel panel_menu2;
    private javax.swing.JPanel panel_peso;
    private javax.swing.JPanel panel_title;
    private javax.swing.JPanel panel_traductor;
    private javax.swing.JTabbedPane paneles;
    private button.MyButton peso;
    private button.MyButton peso1;
    private button.MyButton peso2;
    private combo_suggestion.ComboBoxSuggestion peso_1;
    private combo_suggestion.ComboBoxSuggestion peso_2;
    private javax.swing.JTextArea resultado1;
    private javax.swing.JTextArea resultado2;
    private javax.swing.JScrollPane scroll_resultado;
    private javax.swing.JScrollPane scroll_resultado1;
    private javax.swing.JLabel texto_conversor;
    private javax.swing.JLabel texto_conversor1;
    private javax.swing.JLabel texto_conversor2;
    private javax.swing.JTextField texto_divisa;
    private javax.swing.JTextField texto_peso;
    private javax.swing.JLabel title;
    private button.MyButton traductor;
    private button.MyButton traductor1;
    private button.MyButton traductor2;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/img/panel_1.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);

        }

    }

    class FondoPanel2 extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/img/panel_2.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);

        }

    }

    class FondoPanel3 extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {

            imagen = new ImageIcon(getClass().getResource("/img/panel_3.jpg")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);

        }

    }

}
